config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'
  resources :events do
    resources :comments, only: [:new, :create, :destroy]
  end
  resources :users
  resource :session

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events
  has_many :comments
  validates :username, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :create_new_user
  before_action :set_current_user # Here we're saying "run the method set_current_user before every controller action"

  # not sure you need this here-- I'd just rely on a route going to user#new linked from the application layout
  def create_new_user
    @user = User.new
  end

  def set_current_user
    if User.exists?(session[:user_id]) #if there is a user_id currently stored in the session hash...
      @current_user = User.find(session[:user_id]) #... find and save that in @current_user
    else
      @current_user = nil # ...overwise, set @current_user to nil
    end
  end
end

# I love the concept behind this app-- it's creative and solves an interesting problem in a clever way. really cool project; very clever take on a 2+ model CRUD app. 

# I've included some suggestions for polishing this app through out your project

app/controllers/award_controller.rb
class AwardController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # think you don't need index and show
  def index
  end

  def show

  end

  def new
    @event = Event.find(params[:event_id])
    @comment = @event.comments.new
  end

  def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.create!(comment_params.merge(user: @current_user))
    redirect_to event_path(@event)
  end

  def edit
    # add this here
    # @event = Event.find(params[:event_id])
  end

  def destroy
    @event = Event.find(params[:event_id])
    @comment = @event.comments.find(params[:id])
    @comment.destroy
    redirect_to event_path(@event)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    if @current_user
      @events = @current_user.events
    else
      @events = Event.all
    end
    @user = User.new
  end

  def show
    @event = Event.find(params[:id])
    @comment = Comment.new
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = @current_user.events.create!(event_params)
    @event.save
    redirect_to events_path
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to events_path
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  private
  def event_params
    params.require(:event).permit(:name, :reason, :award)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # nice hand-rolled users and sessions  
  def new
    @user = User.new
  end

  def create
    input_username = params[:user][:username]   # Save the username value submitted through the form

    # If the user exists, sign them in...
    if User.exists?(username: input_username)
      @user = User.find_by(username: input_username)  # Find that user

      # If the password submitted through the form is correct...
      if @user.password == params[:user][:password]
        flash[:notice] = "You're signed in!"
        session[:user_id] = @user.id  # Set the session user_id to that of the user trying to log in
        redirect_to events_path   # Send them back to the app
      else
        flash[:alert] = "Wrong password or Username!"
        redirect_to new_session_path  # Send them back to the sign-in form
      end

    # Otherwise, send them back to the sign-in form so they can enter a valid username-password combination
    else
      flash[:alert] = "That user doesn't exist!"
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session   # Delete all sessions
    flash[:alert] = "You're signed out!"
    redirect_to events_path   # Send the user back to the homepage
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # you can dry up this controller with the following code block
  # before_action :set_user, except: [:index, :new, :create]
  # def set_user
  #     @user = User.find(params[:id])
  # end

  def index
    @users = User.all
  end

  def new
    @user = User.new
    # I would display these in views
    @user.errors.full_messages.first
  end

  def create
    @user = User.create(user_params)
    binding.pry
    if @user.save
      flash[:notice] = "User was successfully created."
      redirect_to events_path
    else
      render :show
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/award_helper.rb
module AwardHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/event/index.html.erb
<h1>Event#index</h1>
<p>Find me in app/views/event/index.html.erb</p>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<!-- I would break this out into a form partial to dry up your new and edit views -->

<div class="new_form">
  <%= form_for @event do |f| %>
    <div>
      <%= f.label :From_who? %>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.label :What_happened_this_time? %>
      <%= f.text_field :reason %>
    </div>

      <%= f.label :I_want %>
    <div class="emoji-picker-container">
      <%= f.text_field :award, class: "text-box", data: { emojiable: true } %>
    </div>

    <div>
      <%= f.submit %>
    </div>
  <% end %>

  <%= form_for @event, method: :delete do |f| %>
    <%= f.submit "Delete this event!", class: "delete", :class => "button" %>
  <% end %>
</div>


<div class="back">
<%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<h1>Emoji Keeper 3000</h1>
<h2 class="description">Keep track of the emojis your friends owe you.</h2>
<h2>
  <% if @current_user %>
  <%= link_to("Add new emoji", new_event_path(@event)) %>
  <%end%>
</h2>

<table align="center" class="feed">
  <% @events.each do |event| %>
    <tr>
      <td class="name"><%= event.name %></td>
      <td class="reason"><%= event.reason %></td>
      <td class="award"><%= event.award %></td>
      <td><%= link_to'Edit', edit_event_path(event) %> | <%= link_to 'Delete', event_path(event), method: :delete, data: { confirm: 'Are you sure?'} %> | <%= link_to 'Comments', event_path(event) %></td>
    </tr>
  <% end %>
</table>

app/views/events/new.html.erb
<h1>New</h1>

<div class="new_form">
  <%= form_for @event do |f| %>

  <div>
    <%= f.label :From_who? %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :What_happened_this_time? %>
    <%= f.text_field :reason %>
  </div>

    <%= f.label :Owes_me %>
  <div class="emoji-picker-container">
    <%= f.text_field :award, class:"text-box", data: { emojiable: true } %>
  </div>

  <div>
    <%= f.submit :class => "button" %>
  </div>
</div>

<% end %>

<div class="back">
<%= link_to 'Back', events_path %>
</div>

app/views/events/show.html.erb
<h1>Comments</h1>

<div class="event">
  <p>
    <strong>Who:</strong>
    <%= @event.name %>
  </p>

  <p>
    <strong>For What:</strong>
    <%= @event.reason %>
  </p>

  <p>
    <strong>Emoji:</strong>
    <%= @event.award %>
  </p>
</div>

<div class="back">
  <%= link_to 'Back', events_path %>
</div>

<h3>Have Something to Say? </h3>

<div class="comments">
  <%= form_for([@event, @comment]) do |f| %>
    <%= f.label :Enter_Here %><br>
  <p class="emoji-picker-container">
    <%= f.text_field :body, class:"text-box", data: { emojiable: true } %>
  </p>

  <p>
    <%= f.submit :class => "button" %>
  </p>
  <% end %>

  <h2>Comments</h2>
  <% @event.comments.each do |comment| %>
  <p>
    <%= comment.body %>
    <%= link_to 'Delete Comment', [comment.event, comment],
    method: :delete,
    data: {confirm: "Are you sure"} %>
  </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch|Indie+Flower|Rock+Salt" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <title>You Owe Me</title>
  </head>

  <body>

    <nav class= "navi">
      <% if @current_user %>
      <%= link_to "Welcome #{@current_user.username}!", user_path(@current_user) %>
      <%= link_to "Sign Out", session_path, method: :delete %>
      <% else %>
      <%= link_to "Sign Up", new_user_path %> |
      <%= link_to "Sign In", new_session_path %>
      <% end %>

      <%= form_for @user, url: session_path, method: :post do |f| %>
        <%= f.label :username %>
        <%= f.text_field :username %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.submit "Submit", :class => "button" %>
      <% end %>

      <br>
      <!-- <%= link_to "Users", users_path %> -->
    </nav>

    <% flash.each do |type, message| %>
      <p class="<%= type %>"><%= message %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h2>Edit Your Profile</h2>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Submit" :class => "button" %>
<% end %>

<div class="back">
  <%= link_to 'Back', events_path %>
</div>

app/views/users/index.html.erb
<h2>Users</h2>

<div class="users">
  <ul>
    <% @users.each do |user| %>
      <li><%= link_to user.username, user %></li>
    <% end %>
  </ul>
</div>

<div class="back">
<%= link_to 'Back', events_path %>
</div>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<div class="new_form">
  <%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit "Submit", :class => "button" %>
  <% end %>
</div>

<br>
<div class="back">
  <%= link_to 'Back', events_path %>
</div>

app/views/users/show.html.erb
<h2>
  <%= @user.username %> <%= link_to"(edit)", edit_user_path(@user)%>
</h2>


<h2><%+ @user.username %> <%= link_to "(edit)", edit_user_path(@user) %></h2>


<div class="back">
<%= link_to 'Back', events_path %>
</div>